-- mod-swipe-fishing: use the salmon relic to start fishing (Salmon Run), instead of /roar.
--
-- Spell 90060 "Salmon Run" is new: it isn't in the stock client or server data. The client gets it
-- from the realm patch (client/build_patch.py adds the same row to Spell.dbc); this row gives the
-- server the same spell. It's a copy of "Dummy Spell" (18282): instant, targets yourself, no cost,
-- a Dummy effect that does nothing, the normal global cooldown, Bear Form or Dire Bear Form only
-- (like Swipe), not in combat, and usable while sitting so using the relic again stops the
-- fishing. Its description is the relics' "Use:" line. The module starts fishing when it's cast.
-- Generated by `python3 client/build_patch.py --from-mpq patch-P.MPQ --sql`; keep the two in step.
--
-- The spell id must match SwipeFishing.SpellId in mod_swipe_fishing.conf.
--
-- Idempotent: safe to run again.

DELETE FROM `spell_dbc` WHERE `ID` = 90060;
INSERT INTO `spell_dbc` VALUES (90060, 0, 0, 0, 402653184, 0, 0, 0, 0, 0, 0, 0, 144, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 101, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 3, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 580, 0, 0, 'Salmon Run', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712190, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 'Call the salmon. Wade into the water and watch; when a salmon surfaces with a splash, Swipe it before it gets away. Use again to stop fishing.', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 16712188, 0, 133, 1500, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.0, 0.0, 0.0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0.0, 0.0, 0.0, 0, 0);

-- Every relic gets Salmon Run as its Use effect, in the second spell slot (the first is the
-- "Equip: Fishing skill increased" spell). Spell and category cooldowns come from the spell: just
-- the global cooldown.

UPDATE `item_template`
SET `spellid_2` = 90060, `spelltrigger_2` = 0, `spellcharges_2` = 0, `spellcooldown_2` = -1,
    `spellcategory_2` = 0, `spellcategorycooldown_2` = -1
WHERE `entry` IN (23004, 42574, 42576, 42577, 25667);

-- Tavar's first quest says to raise the relic rather than to /roar.

UPDATE `quest_template`
SET `QuestDescription` = 'You fish with a pole and a bobber, $N? Like a hairless $r? Hah!$B$BThe bears of this lake taught me better. Wear this old salmon bone, take the shape of the bear, and wade in. Raise the bone to the water, so the salmon know you''ve come. Then sit, and wait, and watch the water.$B$BWhen it splashes, you Swipe. Not before, or you''ll only scare the fish off. Not after, or it''s gone.$B$BCome back to me as your fishing grows. The bone grows with you.'
WHERE `ID` = 9500404;

UPDATE `quest_offer_reward`
SET `RewardText` = 'Wear it well. A bear doesn''t need a pole, and neither do you.$B$BRemember: Bear Form, in the water, and raise the salmon bone. Swipe when the water splashes. Raise it again when you''ve had your fill.'
WHERE `ID` = 9500404;
